- scripts/daily_snapshot/snapshots_prune.rb
Fixes snapshots pruning. When I tested this, I tested it with a `File` class, and the method got a `String` instead. My bad.
> fix snapshots prune

- .github/workflows/docker.yml
- print digest step wasn't showing anything, this PR fixes it.
before:
```
Run echo 
echo 
shell: /usr/bin/bash -e {0}
```
after:
```
Run echo sha256:82999d5b1d2d6c3866f625f758d15d631d08cf4fb5a24f7f5bcff85ed39fdaef
sha256:82999d5b1d2d6c3866f625f758d15d631d08cf
```
Closes 
Context: https://github.com/docker/build-push-action/issues/596#issuecomment-1098561125
> fix digest print

- scripts/sync_check/docker-compose.yml
- scripts/sync_check/health_check.sh
- scripts/sync_check/sync_check_process.rb
- this is a workaround for https://github.com/docker/compose/issues/6975; if we lose the volume, we re-download it. It's not ideal, but hopefully, https://github.com/ChainSafe/forest-iac/issues/42 will mitigate the issue altogether.
- allow for few bootstrap errors before failing the sync check. I guess on calibnet it can happen from time to time.
Closes 
> use `auto-download` for snapshots for sync check

- daily_snapshot_terraform/modules/daily_snapshot/main.tf
- daily_snapshot_terraform/modules/daily_snapshot/prep_sources.sh
- daily_snapshot_terraform/modules/daily_snapshot/service/init.sh
- The terraform module was configured to only re-deploy when the hash of a zip-file changed. Unfortunately, I messed up and the hash would depend on the current time (thus always be unique). Now I'm using a tarball without modification times and it works as intended.
Closes 
> fix: only deploy services when something has changed

- scripts/sync_check/docker-compose.yml
- The default `FACTOR` is 2.0, so the estimated disk usage capacity is abt 120 + 160 + 20 = 300GB. By setting it to 1.4, it's abt 120 + 120 = 240.
- Use 1.2 on calibnet to trigger GC even more eagerly since it takes only 1-2min
Closes 
> feat(sync_check): trigger GC more eagerly to reduce disk usage capacity requirement

- .github/workflows/deploy.yml
- daily_snapshot_terraform/calibnet/README.md
- daily_snapshot_terraform/calibnet/main.tf
- daily_snapshot_terraform/calibnet/variable.tf
- daily_snapshot_terraform/modules/daily_snapshot/main.tf
- daily_snapshot_terraform/modules/daily_snapshot/variable.tf
- Initiate new droplets with SSH fingerprints for everyone who has write-access to our DO account.
This makes it easier for all of us to log into a running droplet. However, it also grants access to, say, Priom (who's head of devops at ChainSafe) even though he's not a member of the Forest team. I think that is fine. Even before adding his key, he could access our droplets through the Droplet Console.
Closes 
> feat: initiate droplets with ssh fingerprints from the entire ChainSafe team

- .github/workflows/deploy.yml
- The SSH key isn't available for first-time contributors. Change the workflow such that the ssh key is only required when we actually deploy (merge to main).
Closes 
> fix: enable ssh-agent only when deploying

- scripts/sync_check/docker-compose.yml
- Save admin token to `/tmp/admin_token` in sync check containers to make it easier to manually execute `forest-cli` commands that require admin permissions
Closes 
> feat(sync_check): save admin token to a temp file

- daily_snapshot_terraform/main.tf
- daily_snapshot_terraform/modules/daily_snapshot/main.tf
- daily_snapshot_terraform/modules/daily_snapshot/variable.tf
- Use the latest release version of Forest instead of the bleeding edge.
- Refactor terraform script to include parameters when deciding whether to redeploy a service.
Closes 
> chore: use the `latest` tag instead of `edge` when generating snapshots

- .github/CODEOWNERS
We've got a new review assignment system - two per PR, which is out-of-repo.
> fix: do not assign everyone to review every pr

- terraform/modules/filecoin_node/lotus.sh
- terraform/modules/filecoin_node/user-data.sh
- Changed  lotus `LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE` to `discard`
Closes 
> fix: discard lotus chainstore splitstore

- sync_check_terraform/modules/sync_check/service/Dockerfile-tester
- sync_check_terraform/modules/sync_check/service/docker-compose.yml
- sync_check_terraform/modules/sync_check/service/init.sh
- sync_check_terraform/modules/sync_check/service/run_service.sh
- sync_check_terraform/modules/sync_check/service/sync_check_process.rb
- this makes the service run on a recent Fedora image but with an older Docker. See https://github.com/docker/compose/issues/10777 that was causing `forest-tester` to fail from time to time. In the end, it should get resolved, but using Fedora packages is safer than the bleeding-edge Docker packages.
Closes 
> use standard fedora docker

- daily_snapshot_terraform/modules/daily_snapshot/service/upload_snapshot.sh
- Locally, I get disconnects and `ChainExchange` failures when the GC runs. Maybe the GC blocks DB access which causes failed p2p responses which leads to disconnecting peers.
Closes 
> fix: disable GCing when exporting a new snapshot

- daily_snapshot_terraform/modules/daily_snapshot/service/list_snapshots.rb
- do_function/snapshot_function/packages/latest-snapshot/link/link.js
- new snapshot files will have the extension `.forest.car.zst`. This PR updates our services to correctly parse such files.
Closes 
> feat: allow snapshot files ending in .forest.car.zst

- .github/workflows/deploy-forest-calibnet.yml
- .github/workflows/deploy-forest-mainnet.yml
- .github/workflows/deploy-lotus-mainnet.yml
- .github/workflows/deploy-new-relic.yml
- .github/workflows/deploy-sync-check.yml
- .github/workflows/deploy.yml
- .github/workflows/deploy_snapshot_function.yml
- Without the lock, we get into data race when one PR that triggers a TF apply is followed by another one. See example:
This rightfully rebuilt `sync-check` given a different dependencies list.
https://github.com/ChainSafe/forest-iac/actions/runs/5627335480/job/15249710896
A minute after this was run, which also detected state diff, and so it triggered a TF at the same time.
https://github.com/ChainSafe/forest-iac/actions/runs/5627341002/job/15249722968
We ended up with two `sync-check` droplets doing the same and having precisely the same state.
Closes 
> allow only one workflow to run concurrently on branch

- terraform/modules/daily_snapshot/service/daily_snapshot.rb
- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- there was a data race in the snapshots directory; mainnet snapshot service was using the same path as the calibnet snapshot, which mounted under the same mount point - this resulted in e.g., validating mainnet snapshots by calibnet snapshot service. It might be the culprit for https://github.com/ChainSafe/forest/issues/3309
Closes 
> fix snapshots data race

- archival-snapshots-generate/src/main.rs
- Diff snapshots may not omit data from _before_ the previous lite snapshot. Fixing this means using the `--diff-depth` flag.
- Include dates in the filenames of diff snapshots.
Closes 
> fix: limit diff depth and use canonical names for diff snapshots

- terraform/modules/sync_check/service/sync_check.rb
- terraform/modules/sync_check/service/sync_check_process.rb
- Update clean command in sync check service
This is for addressing linked comment: https://github.com/ChainSafe/forest-iac/pull/216#discussion_r1296741434
Closes 
> Update clean command in sync check service

- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- this fixes multiple snapshots being uploaded because of errors in previous runs
```
upload: '/root/forest_db/calibnet/forest_snapshot_calibnet_2023-08-21_height_842169.forest.car.sha256sum' -> 's3://forest-snapshots/calibnet/forest_snapshot_calibnet_2023-08-21_height_842169.forest.car.sha256sum' (130 bytes in 0.0 seconds, 4.80 KB/s) [1 of 6]
Public URL of the object is: http://forest-snapshots.fra1.digitaloceanspaces.com/calibnet/forest_snapshot_calibnet_2023-08-21_height_842169.forest.car.sha256sum
upload: '/root/forest_db/calibnet/forest_snapshot_calibnet_2023-08-21_height_842169.forest.car.zst' -> 's3://forest-snapshots/calibnet/forest_snapshot_calibnet_2023-08-21_height_842169.forest.car.zst' (1551778003 bytes in 15.6 …
```
> clean snapshots before snapshot upload

- archival-snapshots-generate/src/main.rs
- `forest-cli archive info` is now `forest-tool archive info`
Closes 
> fix: use the new forest-tool binary

- cf/latest-snapshot/.editorconfig
- cf/latest-snapshot/.prettierrc
- cf/latest-snapshot/README.md
- cf/latest-snapshot/package.json
- cf/latest-snapshot/src/index.ts
- cf/latest-snapshot/tsconfig.json
- cf/latest-snapshot/wrangler.toml
- Define `https://forest-archive.chainsafe.dev/latest/calibnet/` and `https://forest-archive.chainsafe.dev/latest/mainnet/`.
- Both endpoints return the snapshot data directly without any redirects.
Closes
> feat: cf worker for fetching most recent snapshots

- .github/workflows/deploy-benchmark.yml
- the benchmark droplet constantly gets re-created due to minor changes, while the entire benchmark is failing. Let's disable it for now until all issues are resolved.
Closes
> disable daily benchmark

- terraform/modules/benchmark/main.tf
- terraform/modules/benchmark/service/init.sh
- terraform/modules/benchmark/service/lotus_bench.rb
- terraform/modules/benchmark/service/run_benchmark.rb
- terraform/modules/benchmark/variable.tf
- Use a fixed tag for Lotus to avoid any _surprises_
- Try add monitoring like we do for other services (sync check, snapshot export)
Closes #274
We will start with [v1.23.3](https://github.com/filecoin-project/lotus/releases/tag/v1.23.3) and update it manually from time to time (so we can make sure nothing breaks, i.e. change in cli args).
> Use Latest tag for Lotus

- terraform/modules/daily_snapshot/service/daily_snapshot.rb
- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- Let Forest decide on its own where to download snapshots from. This lets us move to CloudFlare when the next Forest version is released.
Closes
> feat: download snapshots from preferred source

- terraform/daily_snapshot/main.tf
- the `s-4vcpu-16gb-amd` droplet is both cheaper and faster than `so-2vcpu-16gb` at exporting. Probably because the SSD is faster. This change should make snapshot exports 10-20 minutes faster.
Closes
> improvement: use cheaper and faster droplet

- terraform/modules/daily_snapshot/service/init.sh
- increase apt-get timeout
With the previous timeout, I still frequently see:
```
+ export DEBIAN_FRONTEND=noninteractive
+ apt-get -qqq --yes -o DPkg::Lock::Timeout=30 update
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 1576 (apt-get)
E: Unable to lock directory /var/lib/apt/lists/
```
Closes
> fix: bump apt-get timeout from 30s to 90s

- terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh
- If no Forest snapshots are upload, upload a FilOps snapshot to CloudFlare rather than DO.
Closes
> fix: upload emergency snapshots to CF rather than DO

- terraform/sync_check/main.tf
- use a smaller VPS for the sync check, as discussed in https://github.com/ChainSafe/forest-iac/pull/289/files#r1345387699
- $47 saved each month ($131 before, $84 after)
Closes
https://slugs.do-api.dev/
> use cheaper droplet for the sync check

- terraform/modules/daily_snapshot/service/mainnet_cron_job
- The mainnet script would accidentally enter an infinite loop if it was invoked more than once. After this PR, the script will exit if invoked twice.
Closes
> fix: exit if cron starts the export script twice

- terraform/modules/daily_snapshot/service/init.sh
- The new version of activesupport isn't backwards compatible
Closes
> fix: pin activesupport to version 7.0.8

- terraform/modules/daily_snapshot/service/init.sh
- terraform/modules/sync_check/service/init.sh
- Cloud-init clashes with our init script. We should wait for the machine to finish initializing before running our own script.
Closes
> fix: wait for cloud-init to finish

- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- Don't show progress when uploading to CloudFlare.
- `aws-cli` likes to generate tens of MiBs of progress messages which aren't useful and just spam the logs.
Closes
> fix: suppress aws upload progress

- terraform/modules/daily_snapshot/service/mainnet_cron_job
- Turns out we don't need that many mainnet snapshots. One per hour is enough.
Closes
> chore: generate at most 1 mainnet snapshot per hour

- terraform/modules/daily_snapshot/service/daily_snapshot.rb
- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- Exporting a calibnet snapshot takes minutes, and a mainnet snapshot takes roughly an hour (sync+export+upload).
- Lower the hard timeout to 8 hours and the sync timeout to 3 hours.
Closes
> chore: lower timeout when exporting snapshots

- terraform/modules/daily_snapshot/service/daily_snapshot.rb
- fixes issues introduced in https://github.com/ChainSafe/forest-iac/pull/315 and  https://github.com/ChainSafe/forest-iac/pull/314; relying on non-standard POSIX behaviour for `sh` and breaking the syntax of a command with too many ticks and quotes.
Closes
> fix snapshot upload escapes bash

- terraform/daily_snapshot/prod/variable.tf
- terraform/daily_snapshot/variable.tf
- terraform/forest-calibnet/variable.tf
- terraform/forest-mainnet/variable.tf
- terraform/modules/daily_snapshot/variable.tf
- terraform/modules/filecoin_node/variable.tf
- terraform/modules/sync_check/variable.tf
- terraform/new-relic/variable.tf
- terraform/sync_check/variable.tf
- Applying some sensible practices from the TF book: make secrets in Terraform variables sensitive so they are not logged when running `plan` or `apply`. This reduces the chance of an accidental secret leak.
Closes
https://developer.hashicorp.com/terraform/tutorials/configuration-language/sensitive-variables
> mark secret variables as sensitive

- cf/latest-snapshot/wrangler.toml
- allow links without trailing slashes. Both `wget https://forest-archive.chainsafe.dev/latest/calibnet` and `wget https://forest-archive.chainsafe.dev/latest/calibnet/` should work now.
Closes https://github.com/ChainSafe/forest-iac/issues/286
> allow no trailing slash latest snapshot link

- terraform/daily_snapshot/prod/main.tf
- pins the snapshot service to `v0.15.0` image of Forest. This is so that Forest breaking releases don't knock-out the service if it's not updated beforehand.
Closes
> pin daily snapshot to forest:v0.15.0

- .github/workflows/deploy-cf-latest-snapshot.yml
- .github/workflows/deploy-cf-prune-latest.yml
- CI/CD for CF workers. It doesn't do any solid testing (https://github.com/ChainSafe/forest-iac/issues/267), but with the `--dry-run`, we are at least able to detect something like, e.g., broken `wrangler.toml`.
Closes
> Cloudflare CI/CD

- .github/workflows/deploy-cf-latest-snapshot.yml
- .github/workflows/deploy-cf-prune-latest.yml
- add account id to CF deployments, given the profile from which the token was generated has multiple accounts.
- allow manually running CF deployments via workflow dispatch
Closes
> add accountid to cf deployments + workflow dispatch

- terraform/daily_snapshot/prod/main.tf
- apparently, a revert https://github.com/ChainSafe/forest-iac/pull/327/commits/d3c24a2f6d8f9edd85c7a4c183c85ccf89d5f5b8 didn't include all necessary changes.
This should fix:
```
│ Warning: Deprecated Parameter
│ 
│   on main.tf line 17, in terraform:
│   17:     endpoint = "https://fra1.digitaloceanspaces.com"
│ 
│ The parameter "endpoint" is deprecated. Use parameter "endpoints.s3"
│ instead.
╵
╷
│ Error: Retrieving AWS account details: AWS account ID not previously found and failed retrieving via all available methods. See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for workaround and implications. Errors: 2 errors occurred:
│ 	* retrieving caller identity from STS: operation error …
```
> fix daily snapshot endpoint

- cf/latest-snapshot/src/index.ts
- support HEAD method for the latest snapshots,
- add `Content-Length`, which was missing before.
Closes
> support HEAD and add content-length

- terraform/daily_snapshot/prod/main.tf
- bumped version of Forest for the daily snapshot service. This is required for a smooth transition between Watermelon and WatermelonFix for the calibration network. See https://github.com/ChainSafe/forest/issues/3632 for more details.
Closes
> bump Forest version for daily snapshot

- cf/latest-snapshot/wrangler.toml
- push the worker logs for the latest snapshot, for analytics
Closes
> push latest-snapshot logs to cloudflare

- terraform/daily_snapshot/prod/main.tf
- Switch back to the ~`latest`~ `v0.16.1` image tag, as `forest@0.16.1` contains necessary fixes/mitigations for the performance issue.
~Let's merge this after `forest@0.16.1` is published.~
Closes
> chore: use latest forest image tag for snapshot service

- terraform/daily_snapshot/main.tf
- terraform/daily_snapshot/prod/main.tf
- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- Use droplet with dedicated CPU resources rather than shared CPU resources.
- Remove work-around for a bug that was fixed.
- Increase sync timeout from 3h to 6h.
Closes
> Use faster droplet for snapshot service

- cf/latest-snapshot/src/index.ts
This lets people resume downloads even if new snapshots are uploaded.
- `/latest/{chain}/` now redirects to `/archive/{chain}/latest/{specific_file.forest.car.zst}`
Closes
> CF: redirect to archive when requesting latest snapshot

- terraform/modules/daily_snapshot/service/daily_snapshot.rb
- We recently introduced an indirection in the snapshot URL. This PR tells our snapshot service to follow indirections.
Closes
> fix: tell curl to follow indirections in the snapshot service

- terraform/daily_snapshot/prod/main.tf
This reverts commit e6b81acda5b6d9d88217a4072bc31a62b41e4689.
- reverts https://github.com/ChainSafe/forest-iac/pull/356. I'm publishing it now so we don't forget about it.
Closes
> Revert "temporarily upgrade snapshot vps (#356)"

- .github/workflows/deploy-snapshot-monitoring.yml
- tf-managed/modules/snapshot-monitoring/README.md
- tf-managed/modules/snapshot-monitoring/main.tf
- tf-managed/modules/snapshot-monitoring/provider.tf
- tf-managed/modules/snapshot-monitoring/variable.tf
- added PagerDuty integration to the snapshot monitor
- we could provide a PagerDuty service, but we'd need an extra-privileged account (or get provided with a relevant API key). Given that it's too much of a hassle for our niche purpose, I created the PD destination manually. We might want to automatize in the future if need be.
Closes https://github.com/ChainSafe/forest-iac/issues/381
> add pagerduty integration

- tf-managed/modules/daily-snapshot/service/upload_snapshot.sh
- downloading proofs takes way too much time than expected. Five minutes is too optimistic. Increasing to 30 minutes.
Note: this should be resolved via https://github.com/ChainSafe/forest-iac/issues/364, given the image should contain all the needed artefacts (within reason). 300 MB worth of proofs is okay.
Closes
> increase calibnet snapshot validation timeout

- tf-managed/modules/sync-check/main.tf
Context: https://github.com/ChainSafe/forest/issues/3892
fat image is now available to save downloading proof parameter files(https://github.com/ChainSafe/forest/pull/3902) and actor bundle(https://github.com/ChainSafe/forest/pull/3904)
- update `forest_tag` in sync check service to use `edge-fat`, see https://github.com/ChainSafe/forest/pkgs/container/forest
Closes
> fix: use edge-fat tag in sync check service

- tf-managed/modules/sync-check/main.tf
- tf-managed/modules/sync-check/variables.tf
- fix sync check wrong variable naming
- fixes sync downtime alert 
Closes
> fix sync check wrong variable naming

- tf-managed/live/environments/prod/applications/snapshot-service/terragrunt.hcl
- update snapshot service Forest to v0.16.6 https://github.com/ChainSafe/forest/releases/tag/v0.16.6
Closes
> update snapshot service Forest to v0.16.6

- tf-managed/modules/forest-droplet/bootstrap.bash.tftpl
- tf-managed/modules/forest-droplet/firewall.tf
- publicly expose p2p port (12345)
- publicly expose metrics port (6116)
- fix rpc port (1234 -> 2345)
Closes
> fix(forest-droplet): publicly expose p2p port

- tf-managed/modules/daily-snapshot/firewall.tf
- tf-managed/modules/daily-snapshot/service/init.sh
- this hopefully will resolve block from the future errors in snapshot service
```
2024-03-18T15:47:08.892094Z  WARN forest_filecoin::chain_sync::chain_muxer: Skipping tipset with invalid block timestamp from the future, now_epoch: 1448349, epoch: 1448349, timestamp: 1710776850
```
Closes
> NTP in snapshot services

- tf-managed/live/environments/dev/applications/forest-butterflynet/terragrunt.hcl
- tf-managed/live/environments/prod/applications/forest-butterflynet/terragrunt.hcl
- tf-managed/modules/forest-droplet/bootstrap.bash.tftpl
- tf-managed/modules/forest-droplet/main.tf
- tf-managed/modules/forest-droplet/variable.tf
- parameterized Forest tag (use `latest-fat` by default) for Forest droplets,
- used recent Forest image for Butterflynet; it was reset on 25.03.2024.
Closes
> Parametrize forest tag

- tf-managed/modules/forest-droplet/bootstrap.bash.tftpl
- without this, the node doesn't seem to be aware that it's running inside a container.
```
/ip4/127.0.0.1/tcp/12345/p2p/12D3KooWNt7gnq5nzTviWwtpjPD3d5NMMBu89RDpExDgU6x3p8QE
/ip4/172.18.0.2/tcp/12345/p2p/12D3KooWNt7gnq5nzTviWwtpjPD3d5NMMBu89RDpExDgU6x3p8QE
```
As an observed result, it doesn't seem to be crawlable, I guess it's related to the DHT table.
Closes
> use host network for filecoin nodes

- tf-managed/modules/daily-snapshot/main.tf
- tf-managed/modules/forest-droplet/main.tf
- tf-managed/modules/sync-check/main.tf
- increase remote exec timeout to 30 minutes
Closes
> fix: increase remote exec timeout to 30 minutes

- cf/forest-snapshot-listing/README.md
- cf/forest-snapshot-listing/src/worker.ts
- cf/forest-snapshot-listing/wrangler.toml
- cf/latest-snapshot/README.md
- cf/latest-snapshot/package-lock.json
- cf/latest-snapshot/wrangler.toml
- cf/prune-latest/wrangler.toml
- images/snapshot-service/src/upload_snapshot.sh
- tf-managed/modules/snapshot-monitoring/README.md
- tf-managed/modules/snapshot-monitoring/snapshot-age-monitor.js
- forest-archive DNS migration to forest-internal
Closes
> chore: forest-archive dns migration to forest-internal

- tf-managed/live/environments/prod/applications/forest-butterflynet/terragrunt.hcl
- tf-managed/live/environments/prod/applications/snapshot-service-2/terragrunt.hcl
- tf-managed/live/environments/prod/applications/snapshot-service/terragrunt.hcl
- updated the Forest tags for snapshot services and Butterfly :butterfly: network.
Closes
> chore: update tags for snapshots and butterfly service

- scripts/mirror-actors/mirror_actors/__main__.py
- there was a package that was use of tag `8.0.0-rc.1` which doesn't start with `v` but also needs to be mirrored. https://github.com/filecoin-project/builtin-actors/releases/tag/8.0.0-rc.1
Closes
> fix: not all releases start with `v`

- tf-managed/modules/sync-check/service/Gemfile
- tf-managed/modules/sync-check/service/Gemfile.lock
- tf-managed/scripts/ruby_common/slack_client.rb
- replaced the deprecated https://api.slack.com/methods/files.upload with a supported API.
- updated Ruby deps
Closes https://github.com/ChainSafe/forest-iac/issues/440
> fix: resolve deprecated Slack files.upload

- tf-managed/modules/sync-check/service/health_check.sh
- the sync checker depends on a metric that I removed. It's better to use 'head_epoch'.
Closes
> fix: replace the deleted 'last_validated_tipset_epoch' metric with 'head_epoch'

- .github/workflows/deploy-sync-check.yml
- composite-action/terragrunt/action.yml
- tf-managed/live/README.md
- removed R2 access secrets occurrences (the one for mirroring actors is still there, which is scoped to the actors bucket).
Closes
> chore: remove R2 access key occurrences

- tf-managed/modules/forest-droplet/bootstrap.bash.tftpl
- tf-managed/modules/sync-check/service/docker-compose.yml
- `FOREST_GC_TRIGGER_FACTOR` is no longer relevant
- set `FOREST_SNAPSHOT_GC_INTERVAL_EPOCHS` to `8640`(3 days) to avoid `Cleaning up sync check` job
Closes
> chore: cleanup stale GC configs
