- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/general_report.md
- .github/ISSUE_TEMPLATE/new_issue.md
- .github/ISSUE_TEMPLATE/task_req.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
Shamelessly copy some GH templates and goodies (dependabot, codewowners) from the Forest repo.
> copy some templates and settings from Forest

- scripts/sync_check/docker-compose.yml
- scripts/sync_check/sync_check_process.rb
- to be reverted after the calibnet is redeemed in Forest.
Closes 
> temporarily disable calibnet

- scripts/sync_check/docker-compose.yml
- scripts/sync_check/sync_check_process.rb
This reverts commit 3f3c65386fbf17b8ad1a763ac7d9ff3b050e6aab.
- re-enable calibnet sync check
Closes 
> Revert "temporarily disable calibnet (#9)"

- scripts/daily_snapshot/upload_snapshot.sh
- 
Fix according to changes implemented here https://github.com/ChainSafe/forest/pull/2039
Closes 
> Fix update snapshot script

- scripts/sync_check/health_check.sh
- fix issue reported by spellcheck which makes the CI red
Closes 
> fix shellcheck issue

- .github/CODEOWNERS
- added @samuelarogbonlo to CODEOWNERS
Closes 
> add @samuelarogbonlo to CODEOWNERS

- scripts/daily_snapshot/boot_service.sh
- scripts/daily_snapshot/upload_snapshot.sh
- scripts/sync_check/run_service.sh
- scripts/sync_check/sync_check_process.rb
- fixed the infrastructure code to work with rootless Forest container
Closes 
https://github.com/ChainSafe/forest/pull/2463
> sync check and daily snapshot for non-root forest

- scripts/sync_check/run_service.sh
- Fixed the permission issue for the sync check. It's not super nice, but it should be fine in our case.
Closes 
> fix permissions issue for sync check

- scripts/daily_snapshot/upload_snapshot.sh
- the CLI changed a bit, requiring passing the chain name. This should be resolved in the future; for now, let's pass it to the binary.
Closes 
https://github.com/ChainSafe/forest/pull/2579
> fix snapshot upload

- scripts/daily_snapshot/upload_snapshot.sh
- use a minimum set of permissions required and only when needed. This will change the modification time of only the latest snapshot which should be okay.
Closes https://github.com/ChainSafe/forest-iac/issues/37
> Preserve modification time

- scripts/Dockerfile-snapshot
- scripts/Dockerfile-sync-check
- hopefully this will add daily snapshot image here https://github.com/orgs/ChainSafe/packages?repo_name=forest-iac
Closes 
> add repo label to images

- .github/workflows/lintingci.yml
- forest-node/terraform/backend.tf
- forest-node/terraform/main.tf
- forest-node/terraform/terraform.tfvars
- Use `terraform fmt` to enforce consistent formatting rules.
Closes 
> Enforce consistent terraform formatting

- scripts/sync_check/sync_check_process.rb
- To give GC task another 16GB space, before we use a larger DO volume
Closes 
> fix(sync_check): adjust cleanup threshold to 0.95

- .github/workflows/deploy.yml
- daily_snapshot_terraform/modules/daily_snapshot/service/init.sh
- Only show the deployment plan if it contains infrastructure changes.
Closes 
> feat: show deployment plan only if it has changed

- scripts/sync_check/sync_check_process.rb
- prune docker images in sync check loop
Closes https://github.com/ChainSafe/forest-iac/issues/66
> feat(sync check): prune docker images in sync check loop

- .github/workflows/deploy.yml
- Searching for comments fails in the main branch.
Closes 
> fix: only look for comments in PRs

- scripts/sync_check/dot-env-template
- changed the `.env` template to use the latest development build of Forest instead of the latest release as per https://github.com/ChainSafe/forest/pull/2770
Closes 
> change default tag for sync test

- .github/workflows/hadolint-ci.yml
- scripts/Dockerfile-sync-check
- scripts/sync_check/Dockerfile-tester
> unpin docker versions

- .github/workflows/lintingci.yml
- Ansible linting no longer works. Disable it until it can be fixed.
Closes 
> Disable ansible linting

- .github/workflows/lintingci.yml
- forest-node/ansible/roles/forest/tasks/main.yml
- forest-node/ansible/roles/letsencrypt/tasks/main.yml
- forest-node/ansible/roles/node_exporter/tasks/main.yml
- forest-node/ansible/roles/observability/tasks/main.yml
- re-enabled Ansible linter and fixed offending issues (naming)
Closes 
> re-enable and fix ansible lint

- daily_snapshot_terraform/modules/daily_snapshot/service/upload_snapshot.sh
- the calibnet snapshot upload is often failing. More detailed logging might help pinpoint the issue (it's only uploaded to Slack in case of a failure anyway).
Closes 
> debug logs for snapshot upload

- .github/workflows/deploy-sync-check.yml
- .github/workflows/deploy.yml
- .github/workflows/deploy_snapshot_function.yml
- This will allow re-deploying services via workflow dispatch.
Closes 
> allow manual deployments via dispatch

- daily_snapshot_terraform/main.tf
- daily_snapshot_terraform/modules/daily_snapshot/variable.tf
- Replace `edge` with `latest`
Closes 
> Use forest latest tag in snapshot service

- daily_snapshot_terraform/modules/daily_snapshot/service/upload_snapshot.sh
- fixed the issue where we end up without Forest logs if the daemon is not able to sync to the HEAD
- applied `shellcheck` suggestions to the existing "script"
Closes 
> improve snapshot error handling + shellcheck

- daily_snapshot_terraform/modules/daily_snapshot/service/upload_snapshot.sh
- add Prometheus metrics to the snapshot logs
Closes 
> add metrics to the snapshot logs

- daily_snapshot_terraform/modules/daily_snapshot/service/upload_snapshot.sh
- we don't want it to be one-off
Closes 
> fix loop condition in metrics

- .github/workflows/lintingci.yml
- daily_snapshot_terraform/main.tf
- daily_snapshot_terraform/modules/daily_snapshot/main.tf
- new-relic/main.tf
- sync_check_terraform/main.tf
- sync_check_terraform/modules/sync_check/main.tf
- sync_check_terraform/modules/sync_check/variable.tf
- sync_check_terraform/variable.tf
- terraform/modules/filecoin_node/main.tf
- Enabled the "terraform lint --recursive" flag for comprehensive linting.
- Resolved all linting errors identified during the process.
Closes #123 
> chore: Implemented the recursive tflint flag and resolved all associated issues

- do_function/snapshot_function/packages/latest-snapshot/link/link.js
- use CDN-enabled link for the latest snapshot redirect
Closes 
> use CDN for snapshots

- do_function/snapshot_function/packages/latest-snapshot/link/link.js
- CDN URLs do not allow listing, falling back to normal links for that.
Closes 
> fix CDN for snapshots

- do_function/snapshot_function/packages/latest-snapshot/link/link.js
> fix fix CDN snapshots

- do_function/snapshot_function/packages/latest-snapshot/link/link.js
> use CDN for listing as well

- do_function/snapshot_function/packages/latest-snapshot/link/link.js
- I get 404s, we can revert the revert later
Closes 
> Revert cdn changes

- daily_snapshot_terraform/modules/daily_snapshot/service/snapshots_prune.rb
- daily_snapshot_terraform/modules/daily_snapshot/service/tests/snapshots_prune_spec.rb
- apparently the CDN is not as agile as we are https://github.com/ChainSafe/forest-iac/pull/155, let's keep a buffer to let it propagate the data
Closes 
> relax pruning to buffer 10 last snapshots

- do_function/snapshot_function/packages/latest-snapshot/link/link.js
This reverts commit 258f82166d4d59e27215aa9cf8238024ae0c29e4.
- after https://github.com/ChainSafe/forest-iac/pull/155 the 404s will hopefully be resolved
Closes 
> Revert "Revert cdn changes (#155)"

- do_function/snapshot_function/packages/latest-snapshot/link/link.js
This reverts commit f79bea9827efb1c1bdd641ffb06bd87c1427633a.
- this is sad
Closes 
> Revert "Revert "Revert cdn changes (#155)" (#158)"

- sync_check_terraform/modules/sync_check/service/docker-compose.yml
- sync_check_terraform/modules/sync_check/service/sync_check_process.rb
> snapshots are no longer in data dir, removed occurrences

- .github/CODEOWNERS
- assign automatically reviewers from the Forest team
- @lemmih I'm not sure if we need to do something in the repo settings as well. Could you please have a look?
Closes 
> assign reviewers automatically

- daily_snapshot_terraform/modules/daily_snapshot/service/upload_snapshot.sh
- Check that snapshots are at least somewhat valid before uploading them.
Closes 
> fix: basic validation of snapshots before they're uploaded

- daily_snapshot_terraform/modules/daily_snapshot/service/upload_snapshot.sh
- Forest requires authorization in order to shutdown
Closes 
> fix: use token for shutdown

- archival-snapshots-generate/README.md
- archival-snapshots-generate/src/main.rs
- fix an off-by-one bug in the diff snapshot generation
Closes 
> fix diff snapshot generation

- terraform/modules/benchmark/service/Dockerfile
- terraform/modules/benchmark/service/benchmark_base.rb
- terraform/modules/benchmark/service/forest_bench.rb
-  Download assets in advance to save git-lfs bandwidth 
Closes 
> Fix git lfs for benchmark service

- composite-action/terraform/action.yml
- terraform/daily_snapshot/.terraform.lock.hcl
- terraform/daily_snapshot/main.tf
- terraform/daily_snapshot/variable.tf
- terraform/modules/daily_snapshot/main.tf
- terraform/modules/daily_snapshot/service/forest-env.tpl
- terraform/modules/daily_snapshot/service/init.sh
- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- terraform/modules/daily_snapshot/variable.tf
- upload snapshots to CloudFlare R2
Files are still uploaded to DO.
Closes #244
> feat: upload snapshots to CloudFlare R2

- archival-snapshots-generate/README.md
- archival-snapshots-generate/src/main.rs
- terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh
- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- change `forest-cli` to `forest-tool` when necessary.
Closes
> chore: update commands to support forest-0.13.0

- cf/prune-latest/README.md
- cf/prune-latest/package.json
- cf/prune-latest/src/index.ts
- cf/prune-latest/tsconfig.json
- cf/prune-latest/wrangler.toml
> feat: cf worker for pruning snapshots

- cf/latest-snapshot/.gitignore
- cf/latest-snapshot/README.md
- cf/latest-snapshot/package-lock.json
- cf/latest-snapshot/package.json
- cf/latest-snapshot/src/index.ts
- cf/latest-snapshot/wrangler.toml
- added range queries support to the latest snapshot worker
- tested with `aria2c -x5` and Brave browser that resumes work correctly,
- enforce `GET` method for all fetches
Closes https://github.com/ChainSafe/forest-iac/issues/264
> CF latest snapshot: support range queries

- terraform/daily_snapshot/README.md
- Add corrections and clarifications to `terraform/daily_snapshot/README.md` discovered during recent Terraform deployments.
N/A
> docs: update terraform `daily_snapshot` README

- .eslintrc.yml
- cf/latest-snapshot/src/index.ts
- cf/prune-latest/src/index.ts
- package.json
- yarn.lock
- enabled TypeScript linting and formatting,
- fixed the offending issues.
Closes https://github.com/ChainSafe/forest-iac/issues/269
> enable typescript linters

- terraform/modules/benchmark/service/run_benchmark.rb
- Add a dedicated `logs` directory
- Clean logs older than one week
Closes
> Clean logs older than one week

- terraform/modules/benchmark/service/bench.rb
- Remove decompression as both client support now .car.zst files
Closes
> Remove snapshot decompressing step

- terraform/modules/daily_snapshot/service/daily_snapshot.rb
- fix invalid location for bash commands.
Closes
> fix: replace fancy bash with dumb bash

- composite-action/terraform/action.yml
- terraform/daily_snapshot/main.tf
- terraform/daily_snapshot/prod/main.tf
- terraform/forest-calibnet/main.tf
- terraform/forest-mainnet/main.tf
- terraform/new-relic/main.tf
- terraform/sync_check/main.tf
- bumps terraform to 1.6.3
Closes https://github.com/ChainSafe/forest-iac/issues/299
> Update Terraform to 1.6.3

- terraform/sync_check/main.tf
- fixes https://github.com/ChainSafe/forest-iac/actions/runs/6784860425/job/18441978098#step:8:60
Closes
> fix backend s3 link

- terraform/daily_snapshot/prod/main.tf
- bumps daily snapshot service to `v0.16.0` which should have calibration network fixed,
Closes
> bump daily snapshot version

- cf/latest-snapshot/README.md
- added `wrangler login` step to the latest snapshot worker readme
Closes
> add login step to CF snapshot readme

- terraform/daily_snapshot/prod/main.tf
- update snapshot service docker image tag to verify the sync perf fix
For more info about the fix, see https://github.com/ChainSafe/forest/pull/3713
Closes
https://github.com/ChainSafe/forest/pkgs/container/forest/147436852?tag=2023-11-14-ddbdbb7
> fix: update snapshot service docker image tag to verify the sync perf fix

- terraform/daily_snapshot/prod/main.tf
- bump Forest to v0.16.2,
Closes
> bump snapshot service to forest 0.16.2

- .github/workflows/deploy-cf-latest-snapshot.yml
- .github/workflows/deploy-cf-prune-latest.yml
- without wildcards the deployments weren't picking changes inside the directory
Closes
> fix CF deployment

- terraform/daily_snapshot/prod/main.tf
- concomitant of https://github.com/ChainSafe/forest/pull/3751
Closes
> use Forest with extended caches for snapshots

- terraform/modules/sync_check/service/sync_check_process.rb
- use a more effective docker volume clean-up method
Closes
> fix: use more effective docker volume clean up method

- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- potentially resolves issues when there weird things happening in the network
Closes
> increase target peer count daily snapshot

- terraform/daily_snapshot/prod/main.tf
- temporarily upgrade the snapshot service worker to be extra powerful for the upcoming Watermelon upgrade. To be reverted afterwards.
Closes
> temporarily upgrade snapshot vps

- scripts/ruby_common/slack_client.rb
- terraform/modules/sync_check/service/sync_check.rb
- terraform/modules/sync_check/service/sync_check_process.rb
- fixes bugs outlined in the linked issue
Closes https://github.com/ChainSafe/forest-iac/issues/343
> fix sync check

- terraform/modules/daily_snapshot/service/upload_snapshot.sh
- use `aria2c` for downloading snapshots, until https://github.com/ChainSafe/forest/issues/3715 is resolved
Closes
> use aria2c for snapshot download

- .github/workflows/scripts-lint.yml
- tf-managed/modules/daily-snapshot/service/daily_snapshot.rb
- tf-managed/modules/sync-check/service/sync_check.rb
- tf-managed/modules/sync-check/service/sync_check_process.rb
- enabled Ruby linter repo-wide
- fixed the rubocop version
- fixed offenses
Closes https://github.com/ChainSafe/forest-iac/issues/82
> enable rubocop repo-wide

- .github/workflows/mirror-builtin-actors.yml
- fix github action cron job trigger event condition
Closes
> fix github action cron job trigger event condition

- tf-managed/modules/daily-snapshot/service/upload_snapshot.sh
- workaround for https://github.com/ChainSafe/forest/issues/3857, until it gets fixed (and even afterwards, because it doesn't hurt and makes the service less vulnerable on Forest internal fiascoes)
Closes
> add timeout to snapshot validations

- .github/workflows/deploy-daily-snapshot.yml
- tf-managed/live/environments/prod/applications/snapshot-service-2/terragrunt.hcl
- adds snapshot service replica for redundancy (should become obsolete once https://github.com/ChainSafe/forest-iac/issues/372 is implemented)
Closes
> add snapshot service replica

- images/snapshot-service/src/upload_snapshot.sh
- snapshot logs are not being uploaded due to docker in docker shenanigans. This PR fixes it.
Closes
> fix snapshot logs upload

- tf-managed/live/environments/prod/applications/snapshot-service-2/terragrunt.hcl
- Move the second snapshot service from France to San Francisco.
Closes
> snapshot service: Move to separate region (fra1 -> sfo3)

- tf-managed/live/environments/prod/applications/snapshot-service-2/terragrunt.hcl
- tf-managed/live/environments/prod/applications/snapshot-service/terragrunt.hcl
- this should fix node getting stuck on bootstraps
Closes
> update forest version in snapshot service to v0.16.7

- tf-managed/live/environments/prod/applications/snapshot-service-2/terragrunt.hcl
- tf-managed/live/environments/prod/applications/snapshot-service/terragrunt.hcl
- update snapshot service Forest to 0.17.0
Closes
> update snapshot service Forest to 0.17.0

- .github/workflows/deploy-forest-butterflynet.yml
- tf-managed/live/environments/dev/applications/forest-butterflynet/terragrunt.hcl
- tf-managed/live/environments/prod/applications/forest-butterflynet/terragrunt.hcl
- run butterflynet node on DO. 2 GB memory and 1 CPU seems to be enough for this network.
Closes
> run butterflynet node

- tf-managed/modules/forest-droplet/bootstrap.bash.tftpl
- listen on all interfaces for the RPC endpoint so that it can be queried externally.
Closes
> listen on all interfaces for RPC

- tf-managed/live/environments/prod/applications/snapshot-service-2/terragrunt.hcl
- tf-managed/live/environments/prod/applications/snapshot-service/terragrunt.hcl
- update Forest to 0.17.1 in snapshot service
Closes
> update Forest to 0.17.1 in snapshot service

- tf-managed/live/environments/prod/applications/snapshot-service-2/terragrunt.hcl
- tf-managed/live/environments/prod/applications/snapshot-service/terragrunt.hcl
- updates nodes to Forest v0.17.2 https://github.com/ChainSafe/forest/pkgs/container/forest/201313688?tag=v0.17.2
Closes
> update snapshot nodes

- FUNDING.json
- same as https://github.com/ChainSafe/forest/pull/4950
Closes
> chore: add funding.json

- tf-managed/live/environments/prod/applications/sync-check/terragrunt.hcl
> fix: sync check droplet size typo

- .github/workflows/deploy-sync-check.yml
- the changes in the workflow should also trigger redeployment, given they might change how the service operates.
Closes
> fix: include workflow in sync check paths
